# Generated by Django 4.0.2 on 2022-05-19 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.AutoField(primary_key=True, serialize=False, verbose_name='Id de la categoria')),
                ('nombre', models.CharField(max_length=15, null=True, verbose_name='Nombre de la categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.AutoField(primary_key=True, serialize=False, verbose_name='Id del producto')),
                ('nombre', models.CharField(max_length=40, null=True, verbose_name='Nombre del producto')),
                ('precio', models.IntegerField(null=True, verbose_name='Precio del producto')),
                ('imagen', models.ImageField(null=True, upload_to='productos')),
                ('stock', models.IntegerField(null=True, verbose_name='Stock del producto')),
                ('descripcion', models.TextField(null=True, verbose_name='Descripcion del producto')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.categoria')),
            ],
        ),
    ]
