# Generated by Django 4.0.2 on 2022-05-20 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('idRegion', models.AutoField(primary_key=True, serialize=False, verbose_name='Id de la region')),
                ('nombre', models.CharField(max_length=30, null=True, verbose_name='Nombre de la region')),
            ],
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('idComuna', models.AutoField(primary_key=True, serialize=False, verbose_name='Id de la comuna')),
                ('nombre', models.CharField(max_length=30, null=True, verbose_name='Nombre de la comuna')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.region')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idCliente', models.AutoField(primary_key=True, serialize=False, verbose_name='Id del cliente')),
                ('nombre', models.CharField(max_length=40, null=True, verbose_name='Nombre del cliente')),
                ('email', models.EmailField(max_length=50, verbose_name='Email del cliente')),
                ('clave', models.CharField(max_length=30, null=True, verbose_name='Clave del cliente')),
                ('direccion', models.CharField(max_length=45, null=True, verbose_name='Direccion del cliente')),
                ('telefono', models.IntegerField(verbose_name='Telefono del cliente')),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.comuna')),
            ],
        ),
    ]
