# Generated by Django 4.0.4 on 2022-07-01 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(max_length=200, null=True, verbose_name='Descripcion del producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcionCorta',
            field=models.TextField(max_length=200, null=True, verbose_name='Descripcion corta del producto'),
        ),
    ]
