# Generated by Django 4.0.2 on 2022-05-20 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_region_comuna_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.CharField(max_length=50, null=True, verbose_name='Email del cliente'),
        ),
    ]
