# Generated by Django 4.0.2 on 2022-05-29 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_cliente_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('idCompra', models.AutoField(primary_key=True, serialize=False, verbose_name='Id de la compra')),
                ('fecha', models.DateField(verbose_name='Fecha de la compra')),
                ('total', models.IntegerField(verbose_name='Total de la compra')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle',
            fields=[
                ('idDetalle', models.AutoField(primary_key=True, serialize=False, verbose_name='Id del detalle')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad del detalle')),
                ('subtotal', models.IntegerField(verbose_name='Subtotal del detalle')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.compra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('idDireccion', models.AutoField(primary_key=True, serialize=False, verbose_name='Id de rol')),
                ('descripcion', models.CharField(max_length=40, null=True, verbose_name='Nombre de la direccion')),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.comuna')),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('idRol', models.AutoField(primary_key=True, serialize=False, verbose_name='Id de rol')),
                ('nombre', models.CharField(max_length=40, null=True, verbose_name='Nombre tipo rol')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('idStatus', models.AutoField(primary_key=True, serialize=False, verbose_name='Id de status')),
                ('nombre', models.CharField(max_length=30, null=True, verbose_name='Nombre del status')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False, verbose_name='Id del usuario')),
                ('nombre', models.CharField(max_length=40, null=True, verbose_name='Nombre del usuario')),
                ('email', models.EmailField(max_length=50, verbose_name='Email del usuario')),
                ('clave', models.CharField(max_length=30, null=True, verbose_name='Clave del usuario')),
                ('telefono', models.IntegerField(verbose_name='Telefono del usuario')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.rol')),
            ],
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.AddField(
            model_name='direccion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario'),
        ),
        migrations.AddField(
            model_name='compra',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.status'),
        ),
        migrations.AddField(
            model_name='compra',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario'),
        ),
    ]
