# Generated by Django 4.0.2 on 2022-05-29 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_compra_detalle_direccion_rol_status_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='status',
            field=models.ForeignKey(default='disponible', on_delete=django.db.models.deletion.PROTECT, to='app.status'),
        ),
    ]
