# Generated by Django 4.0.2 on 2022-05-29 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_producto_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle',
            name='compra',
        ),
        migrations.RemoveField(
            model_name='detalle',
            name='producto',
        ),
        migrations.DeleteModel(
            name='Compra',
        ),
        migrations.DeleteModel(
            name='Detalle',
        ),
    ]
