# Generated by Django 4.0.2 on 2022-05-29 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_producto_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='status',
        ),
    ]
