# Generated by Django 4.0.2 on 2022-05-29 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_producto_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='status',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, to='app.status'),
            preserve_default=False,
        ),
    ]
