# Generated by Django 4.0.4 on 2022-06-01 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_usuario_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descripcionCorta',
            field=models.TextField(null=True, verbose_name='Descripcion corta del producto'),
        ),
    ]
